name: react-native-android-build-apk
on: [push, pull_request]

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        working-directory: ./MobileApp/ReNaApp/
        run: npm install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        working-directory: ./MobileApp/ReNaApp/
        run: npm install    
      - name: Build Android Release
        working-directory: ./MobileApp/ReNaApp/
        run: cd android && chmod +x ./gradlew && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: MobileApp/ReNaApp/android/app/build/outputs/apk/release/
